// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/gails/runtime.js";

/**
 * Marshaler is the interface implemented by types that
 * can marshal themselves into valid JSON.
 */
export type Marshaler = any;
