// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/gails/runtime.js";

/**
 * TextMarshaler is the interface implemented by an object that can
 * marshal itself into a textual form.
 * 
 * MarshalText encodes the receiver into UTF-8-encoded text and returns the result.
 */
export type TextMarshaler = any;
