package commands

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

func TestRepoRootFrom(t *testing.T) {
	cases := []struct {
		name    string
		setup   func(t *testing.T) string // returns probe path
		want    string                    // expected root, "" = expect error
		wantErr bool
	}{
		{
			name: "finds root with v3/internal/commands as direct child",
			setup: func(t *testing.T) string {
				root := t.TempDir()
				if err := os.MkdirAll(filepath.Join(root, "v3", "internal", "commands"), 0o755); err != nil {
					t.Fatal(err)
				}
				return root
			},
			want: "", // we assert on equality below
		},
		{
			name: "walks up one level",
			setup: func(t *testing.T) string {
				root := t.TempDir()
				if err := os.MkdirAll(filepath.Join(root, "v3", "internal", "commands"), 0o755); err != nil {
					t.Fatal(err)
				}
				// Probe is one level deeper than root
				deeper := filepath.Join(root, "subdir", "deeper")
				if err := os.MkdirAll(deeper, 0o755); err != nil {
					t.Fatal(err)
				}
				return deeper
			},
			// We expect the walker to find root by walking up
			want: "",
		},
		{
			name: "returns error when v3/internal/commands not found within 10 levels",
			setup: func(t *testing.T) string {
				return t.TempDir()
			},
			wantErr: true,
		},
		{
			name: "empty probe (filesystem root) returns error after 10 iterations",
			setup: func(t *testing.T) string {
				return "/"
			},
			wantErr: true,
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			probe := tc.setup(t)
			got, err := repoRootFrom(probe)
			if (err != nil) != tc.wantErr {
				t.Errorf("err = %v, wantErr = %v", err, tc.wantErr)
			}
			if tc.wantErr {
				return
			}
			// Assert the returned path contains v3/internal/commands
			wantPath := filepath.Join(got, "v3", "internal", "commands")
			if _, err := os.Stat(wantPath); err != nil {
				t.Errorf("returned root %q does not contain v3/internal/commands: %v", got, err)
			}
		})
	}
}

func TestIOSOverlayGen_EmptyOut(t *testing.T) {
	err := IOSOverlayGen(&IOSOverlayGenOptions{Out: ""})
	if err == nil {
		t.Fatal("expected error for empty --out, got nil")
	}
}

// TestIOSOverlayGen_WritesOverlay covers the happy path: scaffold a fake
// repo root with the v3/internal/commands/build_assets/ios/main_ios.go
// template, call IOSOverlayGen, and assert both files were created.
func TestIOSOverlayGen_WritesOverlay(t *testing.T) {
	root := t.TempDir()
	tmplDir := filepath.Join(root, "v3", "internal", "commands", "build_assets", "ios")
	if err := os.MkdirAll(tmplDir, 0o755); err != nil {
		t.Fatal(err)
	}
	tmplContent := []byte("package main\n// generated by test\n")
	if err := os.WriteFile(filepath.Join(tmplDir, "main_ios.go"), tmplContent, 0o644); err != nil {
		t.Fatal(err)
	}

	// IOSOverlayGen uses os.Getwd() internally; chdir into a fresh dir
	// so the test doesn't pollute the user's real cwd.
	appDir := t.TempDir()
	prevCwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(prevCwd) })
	if err := os.Chdir(appDir); err != nil {
		t.Fatal(err)
	}

	// Stub repoRoot to return our fixture root. We can't change the
	// package-level repoRoot; instead we chdir to a position where
	// repoRoot() (which uses Getwd) would find our fixture. To do that
	// we walk up: probe is a deep tempdir that has v3/... under it.
	// Easier: make a parent that contains the v3 dir.
	parent := filepath.Dir(appDir) // appDir is e.g. /tmp/xxx/001, parent is /tmp/xxx
	// Move the v3 dir from root to parent. We already created it under
	// root; move it.
	if err := os.Rename(filepath.Join(root, "v3"), filepath.Join(parent, "v3")); err != nil {
		t.Fatalf("rename v3: %v", err)
	}
	// Now chdir to a deeper path so repoRoot walks up to find v3/
	deeperCwd := filepath.Join(parent, "v3", "internal", "commands")
	if err := os.Chdir(deeperCwd); err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(appDir, "overlay.json")
	if err := IOSOverlayGen(&IOSOverlayGenOptions{Out: out}); err != nil {
		t.Fatalf("IOSOverlayGen: %v", err)
	}

	// overlay.json must exist and be valid JSON
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("read overlay: %v", err)
	}
	var ov struct {
		Replace map[string]string `json:"Replace"`
	}
	if err := json.Unmarshal(data, &ov); err != nil {
		t.Fatalf("overlay not valid JSON: %v\n-- got --\n%s", err, data)
	}
	if len(ov.Replace) != 1 {
		t.Errorf("expected 1 Replace entry, got %d (%v)", len(ov.Replace), ov.Replace)
	}
	// The value should point to a gen file that exists
	for virtual, real := range ov.Replace {
		if virtual == "" || real == "" {
			t.Errorf("empty virtual or real path: %v -> %v", virtual, real)
		}
		if _, err := os.Stat(real); err != nil {
			t.Errorf("real gen file does not exist: %v", err)
		}
	}
}
