// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/gails/runtime.js";

export type Alias = Cyclic | null;

export type Cyclic = { [_ in string]?: Alias }[];

export type GenericCyclic<T> = {"X": GenericCyclic<T> | null, "Y": T[]}[];
